#!/bin/sh /etc/rc.common
# Basic init script for Domo system
# February 2015, Suxsem

START=81
APP=/root/mqtt_client/mqtt_scattato.lua

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_MATCH_EXEC=

start() {
        service_check $APP && return 1
        cd /root/mqtt_client/
        service_start $APP
}

stop() {
        service_stop $APP
}